<?php

use Illuminate\Database\Seeder;
use App\Model\GeneralSetup\Document;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Document::truncate();

        /* $documents = array(
            array('id' => '1','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_1','file_code' => 'dfc-000001','file_name' => 'Please Attach Necessary Documents<br/>(eg. You ID)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 03:59:48','updated_at' => '2021-07-31 20:59:49'),
            array('id' => '2','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_2','file_code' => 'dfc-000002','file_name' => 'Necessary Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:02:35','updated_at' => '2021-07-31 21:11:12'),
            array('id' => '3','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_4','file_code' => 'dfc-000003','file_name' => 'Lay Out Of Premises','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimetypes:video/*,video/x-m4v,video/mp4,video/x-m4v,video/x-matroska','file_type' => 'Video','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:02:22','updated_at' => '2021-07-31 21:11:21'),
            array('id' => '4','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_4','file_code' => 'dfc-000004','file_name' => 'Blue Print Of the Sections','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '1','min_size' => '2','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:01:50','updated_at' => '2021-07-31 21:11:28'),
            array('id' => '5','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_4','file_code' => 'dfc-000005','file_name' => 'Specification Of the Storage Accommodation(s)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:05:57','updated_at' => '2021-07-31 21:13:18'),
            array('id' => '6','application_module_id' => '1','sub_type' => 'new','addition_filter' => 'step_4','file_code' => 'dfc-000006','file_name' => 'Equiments, Instrument Applicance List','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '7','application_module_id' => '2','sub_type' => 'new','addition_filter' => 'step_4','file_code' => 'dfc-000007','file_name' => 'Sample Receipt','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '8','application_module_id' => '2','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000008','file_name' => 'ADM-A3','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '9','application_module_id' => '2','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000009','file_name' => 'QUA-PIIP-1','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '10','application_module_id' => '2','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000010','file_name' => 'CLI-PIVO (clinical overview)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '11','application_module_id' => '2','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000011','file_name' => 'NCLI-PABA-3 (non clinical)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            //application_module_id 4 (dlmc)
            array('id' => '12','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_1','file_code' => 'dfc-000012','file_name' => 'Please Attach Necessary Documents (eg. Company Licence No)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '13','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_2','file_code' => 'dfc-000013','file_name' => 'Please Attach Necessary Documents (eg. Company Licence No)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '14','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_3','file_code' => 'dfc-000014','file_name' => 'Table of constitution ( Organization Chart )','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '15','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_3','file_code' => 'dfc-000015','file_name' => 'Experience in years , duties','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '16','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000016','file_name' => 'Implementation process and records', 'group_name' => 'Factory Sanitation System', 'require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '17','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000017','file_name' => 'Production manual, records and SOP', 'group_name' => 'Records and Documents', 'require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '18','application_module_id' => '4','sub_type' => 'new','addition_filter' => 'step_5','file_code' => 'dfc-000018','file_name' => 'QC Check record and SOP', 'group_name' => 'Records and Documents', 'require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
        // ##### One Time start ##### //
            //// onetime step 1

                // >>special manual<<
                array('id' => '19','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_0','file_code' => 'dfc-000019','file_name' => 'Drug Registration Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '20','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_0_1','file_code' => 'dfc-000020','file_name' => 'Drug Registration Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // >>renew manual<<
                array('id' => '21','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_1','file_code' => 'dfc-000021','file_name' => 'Drug Registration Old Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '22','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_1','file_code' => 'dfc-000022','file_name' => 'Assessment Fees and Fine Fees Payment Receive Form (If Late Fee)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '23','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_1','file_code' => 'dfc-000023','file_name' => 'Preview Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // normal step file
                array('id' => '24','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_2','file_code' => 'dfc-000024','file_name' => 'NRA (Certificate Number)','require' => 'no','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '25','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_2','file_code' => 'dfc-000025','file_name' => 'Certificate of Analysis (COA)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '26','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_2','file_code' => 'dfc-000026','file_name' => 'Good Manufacruring Practic (GMP)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '27','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_2','file_code' => 'dfc-000027','file_name' => 'Manufacturer Licence','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // array('id' => '28','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1_2','file_code' => 'dfc-000028','file_name' => 'WHO Certificate','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            ////// onetime step 2
                //nrc
                array('id' => '29','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_2','file_code' => 'dfc-000029','file_name' => 'Please Attach Necessary Documents (eg. Your ID)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // special & drc-renew manual
                array('id' => '30','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_2_0','file_code' => 'dfc-000030','file_name' => 'Drug Importation Approval Certificate -DIAC','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // diac-renew manual
                array('id' => '31','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_2_1','file_code' => 'dfc-000031','file_name' => 'Drug Importation Approval Old Certificate -DIAC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '32','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_2_1','file_code' => 'dfc-000032','file_name' => 'Assessment Fees and Fine Fees Payment Receive Form','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '33','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_2_1','file_code' => 'dfc-000033','file_name' => 'Preview Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            ////// onetime step 3
                array('id' => '34','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_3','file_code' => 'dfc-000034','file_name' => 'LOA form legal Manufacture','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // array('id' => '35','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_3','file_code' => 'dfc-000035','file_name' => 'Wearhouse','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimetypes:video/*,video/x-m4v,video/mp4,video/x-m4v,video/x-matroska','file_type' => 'Video','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:02:22','updated_at' => '2021-07-31 21:11:21'),
                array('id' => '36','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_3','file_code' => 'dfc-000036','file_name' => 'Others','require' => 'no','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '2','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '2','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                // >> product info <<
                array('id' => '37','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1','file_code' => 'dfc-000037','file_name' => 'Direction of Use (Indication)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
                array('id' => '38','application_module_id' => '5','sub_type' => 'new','addition_filter' => 'step_1','file_code' => 'dfc-000038','file_name' => 'Packaging and Number of Units','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','mimes' => 'mimes:pdf','file_type' => 'PDF','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
        //###### onetime end #########
        ); */

        $documents = array(
            array('id' => '1','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000001','file_name' => 'Please Attach Necessary Documents<br/>(eg. You ID)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 03:59:48','updated_at' => '2021-07-31 20:59:49'),
            array('id' => '2','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2','file_code' => 'dfc-000002','file_name' => 'Necessary Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:02:35','updated_at' => '2021-07-31 21:11:12'),
            array('id' => '3','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000003','file_name' => 'Lay Out(<i>Not more than 15 minutes</i>)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'Video','mimes' => 'mimetypes:video/*,video/x-m4v,video/mp4,video/x-m4v,video/x-matroska','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:02:22','updated_at' => '2021-09-27 06:43:04'),
            array('id' => '4','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000004','file_name' => 'Blue Print Of the Sections','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '1','min_size' => '2','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'deleted','created_at' => '2021-07-19 04:01:50','updated_at' => '2021-09-27 06:43:18'),
            array('id' => '5','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000005','file_name' => 'Specification Of the Storage Accommodation(s)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:05:57','updated_at' => '2021-07-31 21:13:18'),
            array('id' => '6','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000006','file_name' => 'Equiments, Instrument Applicance List','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '7','application_module_id' => '2','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000007','file_name' => 'Sample Receipt','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '8','application_module_id' => '2','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_5','file_code' => 'dfc-000008','file_name' => 'ADM-A3','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '9','application_module_id' => '2','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_5','file_code' => 'dfc-000009','file_name' => 'QUA-PIIP-1','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '10','application_module_id' => '2','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_5','file_code' => 'dfc-000010','file_name' => 'CLI-PIVO (clinical overview)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '11','application_module_id' => '2','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_5','file_code' => 'dfc-000011','file_name' => 'NCLI-PABA-3 (non clinical)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '12','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000012','file_name' => 'Please Attach Necessary Documents (eg. Company Licence No)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '13','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2','file_code' => 'dfc-000013','file_name' => 'Please Attach Necessary Documents (eg. Company Licence No)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '14','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000014','file_name' => 'Table of constitution ( Organization Chart )','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '15','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000015','file_name' => 'Experience in years , duties','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '16','application_module_id' => '4','sub_type' => 'new','group_name' => 'Factory Sanitation System','addition_filter' => 'step_5','file_code' => 'dfc-000016','file_name' => 'Implementation process and records','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '17','application_module_id' => '4','sub_type' => 'new','group_name' => 'Records and Documents','addition_filter' => 'step_5','file_code' => 'dfc-000017','file_name' => 'Production manual, records and SOP','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '18','application_module_id' => '4','sub_type' => 'new','group_name' => 'Records and Documents','addition_filter' => 'step_5','file_code' => 'dfc-000018','file_name' => 'QC Check record and SOP','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '19','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_0','file_code' => 'dfc-000019','file_name' => 'Drug Registration Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '20','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_0_1','file_code' => 'dfc-000020','file_name' => 'Drug Registration Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '21','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_1','file_code' => 'dfc-000021','file_name' => 'Drug Registration Old Certificate - DRC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '22','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_1','file_code' => 'dfc-000022','file_name' => 'Assessment Fees and Fine Fees Payment Receive Form (If Late Fee)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '23','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_1','file_code' => 'dfc-000023','file_name' => 'Preview Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '24','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_2','file_code' => 'dfc-000024','file_name' => 'NRA (Certificate Number)','require' => 'no','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '25','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_2','file_code' => 'dfc-000025','file_name' => 'Certificate of Analysis (COA)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '26','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_2','file_code' => 'dfc-000026','file_name' => 'Good Manufacruring Practic (GMP)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '27','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1_2','file_code' => 'dfc-000027','file_name' => 'Manufacturer Licence','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '28','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2','file_code' => 'dfc-000029','file_name' => 'Please Attach Necessary Documents (eg. Your ID)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '29','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2_0','file_code' => 'dfc-000030','file_name' => 'Drug Importation Approval Certificate -DIAC','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '30','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2_1','file_code' => 'dfc-000031','file_name' => 'Drug Importation Approval Old Certificate -DIAC (Import)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '31','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2_1','file_code' => 'dfc-000032','file_name' => 'Assessment Fees and Fine Fees Payment Receive Form','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '32','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_2_1','file_code' => 'dfc-000033','file_name' => 'Preview Document','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '33','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000034','file_name' => 'LOA form legal Manufacture','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '34','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000036','file_name' => 'Others','require' => 'no','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '2','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '2','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '35','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000037','file_name' => 'Direction of Use (Indication)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '36','application_module_id' => '5','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000038','file_name' => 'Packaging and Number of Units','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-07-19 04:08:14','updated_at' => '2021-07-31 21:11:39'),
            array('id' => '37','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000039','file_name' => 'Factory Area (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:31:48','updated_at' => '2021-09-27 06:31:48'),
            array('id' => '38','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000040','file_name' => 'Room for every production step (Video Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'Video','mimes' => 'mimetypes:video/*,video/x-m4v,video/mp4,video/x-m4v,video/x-matroska','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:33:31','updated_at' => '2021-09-27 06:33:31'),
            array('id' => '39','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000041','file_name' => 'Brief Description of Ventilation System (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:35:52','updated_at' => '2021-09-27 06:36:17'),
            array('id' => '40','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000042','file_name' => 'Handling of high-priority Toxic  Materials (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:36:50','updated_at' => '2021-09-27 06:36:50'),
            array('id' => '41','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000043','file_name' => 'Summary of factory Water Supply System (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:37:47','updated_at' => '2021-09-27 06:37:47'),
            array('id' => '42','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000044','file_name' => 'Factory Renovation and Maintenance Record (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:38:53','updated_at' => '2021-09-27 06:38:53'),
            array('id' => '43','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000045','file_name' => 'Coordination with Outside Laboratories (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:39:28','updated_at' => '2021-09-27 06:39:28'),
            array('id' => '44','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000046','file_name' => 'Summary of quality management system (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:40:13','updated_at' => '2021-09-27 06:40:13'),
            array('id' => '45','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000047','file_name' => 'Main machinery (production and quality control) (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:41:04','updated_at' => '2021-09-27 06:41:04'),
            array('id' => '46','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000048','file_name' => 'Records for machinery maintenance (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:41:39','updated_at' => '2021-09-27 06:41:39'),
            array('id' => '47','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_1','file_code' => 'dfc-000049','file_name' => 'Quality of machinery and their maintenance records for calibration (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:42:18','updated_at' => '2021-09-27 06:42:18'),
            array('id' => '48','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000050','file_name' => 'Trainning ( On-job training,fire prevention training, red cross training) (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:43:24','updated_at' => '2021-09-27 06:43:24'),
            array('id' => '49','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000051','file_name' => 'Medical check up (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:43:56','updated_at' => '2021-09-27 06:43:56'),
            array('id' => '50','application_module_id' => '4','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_3','file_code' => 'dfc-000052','file_name' => 'Personal Hygience ( Factory Uniform ) (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:44:31','updated_at' => '2021-09-27 06:44:31'),
            array('id' => '51','application_module_id' => '4','sub_type' => 'new','group_name' => 'Production','addition_filter' => 'step_5','file_code' => 'dfc-000053','file_name' => 'Procedures of productions (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:45:56','updated_at' => '2021-09-27 06:45:56'),
            array('id' => '52','application_module_id' => '4','sub_type' => 'new','group_name' => 'Production','addition_filter' => 'step_5','file_code' => 'dfc-000054','file_name' => 'Storage of raw materials of pharmaceuticals, packaging process (sampling), differentiating and storage distribution (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:46:34','updated_at' => '2021-09-27 06:46:34'),
            array('id' => '53','application_module_id' => '4','sub_type' => 'new','group_name' => 'Production','addition_filter' => 'step_5','file_code' => 'dfc-000055','file_name' => 'Handling of rejected pharmaceutical products / medicines (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:47:25','updated_at' => '2021-09-27 06:47:25'),
            array('id' => '54','application_module_id' => '4','sub_type' => 'new','group_name' => 'Quality Control','addition_filter' => 'step_5','file_code' => 'dfc-000056','file_name' => 'Process of getting laboratory approval   (PDF only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:48:10','updated_at' => '2021-09-27 06:48:10'),
            array('id' => '55','application_module_id' => '4','sub_type' => 'new','group_name' => 'Distribution, Complaint and withdrawal from market','addition_filter' => 'step_5','file_code' => 'dfc-000057','file_name' => 'Implementation process and records (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:48:54','updated_at' => '2021-09-27 06:48:54'),
            array('id' => '56','application_module_id' => '4','sub_type' => 'new','group_name' => 'Distribution, Complaint and withdrawal from market','addition_filter' => 'step_5','file_code' => 'dfc-000058','file_name' => 'The processes of accepting the complaint, withdrawal of products from the market and respective procedures (in align with GMP, the pharmaceutical companies should be located  in Factory zones, far form civilian wards)  (PDF Only)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => 'PDF','mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-27 06:49:38','updated_at' => '2021-09-27 06:49:38'),
            array('id' => '57','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000059','file_name' => 'LOA','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 17:30:00','updated_at' => '2021-09-28 18:05:36'),
            array('id' => '58','application_module_id' => '2','sub_type' => 'new','group_name' => 'Administrative','addition_filter' => 'step_5','file_code' => 'dfc-000060','file_name' => 'Letter of Authorization','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 17:42:58','updated_at' => '2021-09-28 17:42:58'),
            array('id' => '59','application_module_id' => '2','sub_type' => 'new','group_name' => 'Quality','addition_filter' => 'step_5','file_code' => 'dfc-000061','file_name' => 'QUA-PIIP2 ( Pharmaceutical development )','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 17:44:23','updated_at' => '2021-09-28 17:44:23'),
            array('id' => '60','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000062','file_name' => 'Myanmar Pharmaceutical Member Copy','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 17:48:32','updated_at' => '2021-09-28 17:50:56'),
            array('id' => '61','application_module_id' => '1','sub_type' => 'new','group_name' => NULL,'addition_filter' => 'step_4','file_code' => 'dfc-000063','file_name' => 'Consignee Calculation for Storage','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 17:49:36','updated_at' => '2021-09-28 17:51:10'),
            array('id' => '62','application_module_id' => '2','sub_type' => 'new','group_name' => 'Non-Clinical','addition_filter' => 'step_5','file_code' => 'dfc-000064','file_name' => 'NCLI-P3AB ( Non-Clinical, General Aspect and Content and Structural Format )','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 19:28:29','updated_at' => '2021-09-28 19:28:29'),
            array('id' => '63','application_module_id' => '2','sub_type' => 'new','group_name' => 'Non-Clinical','addition_filter' => 'step_5','file_code' => 'dfc-000065','file_name' => 'NCLI-P3AB ( Non-Clinical, General Aspect and Content and Structural Format )','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 19:28:29','updated_at' => '2021-09-28 19:28:29'),
            array('id' => '64','application_module_id' => '2','sub_type' => 'new','group_name' => 'Administrative','addition_filter' => 'step_5','file_code' => 'dfc-000066','file_name' => 'License of pharmaceutical industries/ importer/ wholesaler (country specific)','require' => 'yes','require_if' => NULL,'uploadable_type' => 'single','max_size' => '5','min_size' => '1','file_type' => NULL,'mimes' => 'mimes:pdf','uploadable_file_count' => '1','status' => 'active','created_at' => '2021-09-28 19:28:29','updated_at' => '2021-09-28 19:28:29'),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Administrative',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000067',
                'file_name' => 'Certificate of Pharmaceutical Product issued by the competent authority in the country of origin according to the current WHO format',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Administrative',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000068',
                'file_name' => 'Site master file of manufacturer (unless previously submitted within the last 2 years)(country specific)',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Administrative',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000069',
                'file_name' => 'Product Information for package insert (required for generic products)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000070',
                'file_name' => 'General Information of Nomenclature (information from the SI)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000071',
                'file_name' => 'Structure Information (Structural formula, including relative and absolute stereochemistry, the molecular formula, and the relativce molecular mass)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000072',
                'file_name' => 'General properties for physico chemical characteristics and other relevant properties including biological activity for biotech',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000073',
                'file_name' => 'General properties for schematic amino acid sequence indicationg glycosylation sites or the post-translation modifications and relative molecular mass as appropriate',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000074',
                'file_name' => 'Name and address of the manufacturer(s)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000075',
                'file_name' => 'Elucidation of Structure and other characteristics',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Quality',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000076',
                'file_name' => 'Stability (literature data)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000077',
                'file_name' => 'Dosage form and characteristics',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000078',
                'file_name' => 'Accompanying reconstitution diluent(s) if any',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000079',
                'file_name' => 'Type of container and closure used for the dosage form and reconstitution diluent, if applicable',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000080',
                'file_name' => 'Name and quality stated in metric weight or measures, function and quality',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000081',
                'file_name' => 'Active Ingredient (literature data)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000082',
                'file_name' => 'Justification of nay overage in the formulation(s)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000083',
                'file_name' => 'Physicochemical and Biological Properties',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000084',
                'file_name' => 'Parameters relevant to the performance of the finished product e.g pH, dissolution',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000085',
                'file_name' => 'Selection and optimisation of the manufacturing process',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000086',
                'file_name' => 'Suitability of the container closure system used for the storage, transportation (shipping) and use of the finished product',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000087',
                'file_name' => 'Microbiological attributes fo the dosage form, where appropriate',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000088',
                'file_name' => 'Batch formula (name and quantities of all ingredients)',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000089',
                'file_name' => 'Description of manufacturing process and process control',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000090',
                'file_name' => 'Control of Critical Steps and Intermediates (Tests and acceptance criteria)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000091',
                'file_name' => 'Description documentation and results fo the validation and evaluation studies',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000092',
                'file_name' => 'Analytical Procedure (Compendial requirements or appropriate information from manufacturers',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000093',
                'file_name' => 'Specification for the finished product',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000094',
                'file_name' => 'Analytical procedures used for testing finished product',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000095',
                'file_name' => 'Non Compendial Method',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000096',
                'file_name' => 'Verification of compendial method applicability-precision & accuracy',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000097',
                'file_name' => 'Description and test results of all relevant batches',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000098',
                'file_name' => 'Compendial requirements or appropriate information',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000099',
                'file_name' => 'Justification of the Proposal finished product specification',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000100',
                'file_name' => 'Specification and control of primary and secondary packaging material, packaging type and size, details of packaging inclusion (e.g. desiccant, etc)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000101',
                'file_name' => 'Stability report (data demonstrating that product is stable through its proposed shelf life)',
                'require' => 'yes',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000102',
                'file_name' => 'Commitment on post approval stability monitoring',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000103',
                'file_name' => 'Equivalence evidence (In Vitro - Comparative dissolution study as required)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),
            array(
                'application_module_id' => '2',
                'sub_type' => 'new',
                'group_name' => 'Product',
                'addition_filter' => 'step_5',
                'file_code' => 'dfc-000104',
                'file_name' => 'Equivalence evidence (In Vivo - Bioequivalence study as required)',
                'require' => 'no',
                'require_if' => NULL,
                'uploadable_type' => 'single',
                'max_size' => '5',
                'min_size' => '1',
                'file_type' => NULL,
                'mimes' => 'mimes:pdf',
                'uploadable_file_count' => '1',
                'status' => 'active'
            ),



        );

        foreach($documents as $document) {
            unset($document['id']);
            Document::create($document);
        }

    }
}
