<?php

use Illuminate\Database\Seeder;
use App\Model\ProductSetup\PrimaryContainer;

class PrimaryContainerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        PrimaryContainer::truncate();

        $primary_containers = array(
            array('ctg_env_id' => '2','ctg_env_desc' => 'Bag','ctg_env_obs' => 'Container consisting of surfaces, whether or not with a flat bottom, made of flexible material, generally closed at the bottom and at the sides by sealing; at the top possibly to be closed by fusion of the material, depending on the intended use. Equ','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '3','ctg_env_desc' => 'Barrel','ctg_env_obs' => 'Container of large size, suited for liquid, solid and semi-solid pharmaceutical forms.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '4','ctg_env_desc' => 'Blister','ctg_env_obs' => 'Container (usually multidose) consisting of two layers of which one is shaped to contain the individual doses. Strips and unit-dose blisters are excluded.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '5','ctg_env_desc' => 'Bottle','ctg_env_obs' => 'Container with a more or less pronounced neck and usually a flat bottom.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '6','ctg_env_desc' => 'Box','ctg_env_obs' => 'Primary container consisting of one or more parts made of a light material, can be closed.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '7','ctg_env_desc' => 'Cartridge','ctg_env_obs' => 'Usually cylindrical, suited for liquid or solid pharmaceutical forms; usually to be used in an apparatus especially designed for that purpose. It contains the final preparation in one compartment, or the components necessary for its preparation in di','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '8','ctg_env_desc' => 'Container','ctg_env_obs' => 'An item of packaging that is used for the storage, identification and/or transport of a medicinal product. Only to be used where more-specific terms do not apply. Specific characteristics of the container are defined in the product information of the','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '9','ctg_env_desc' => 'Dose-dispenser cartridge','ctg_env_obs' => 'Container intended for use in a dose dispenser, usually pre-filled with a medicinal product.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '11','ctg_env_desc' => 'Dropper container','ctg_env_obs' => 'A container, usually a bottle, fitted with a dropper applicator.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '13','ctg_env_desc' => 'Gas cylinder','ctg_env_obs' => 'Container usually cylindrical suited for compressed, liquefied or dissolved gas, fitted with a device to regulate the spontaneous outflow of gas at atmospheric pressure and room temperature.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '14','ctg_env_desc' => 'Jar','ctg_env_obs' => 'Container, without a pronounced neck, with a wide opening at the top and a more-or-less flat bottom. It is suited for semi-solid and solid pharmaceutical forms (including those that are stored/supplied in a liquid medium, such as living tissue equiva','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '15','ctg_env_desc' => 'Mobile cryogenic vessel','ctg_env_obs' => 'A mobile thermally insulated container designed to maintain the contents in a liquid state.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '16','ctg_env_desc' => 'Multidose container','ctg_env_obs' => 'A container holding a quantity of the preparation suitable for 2 or more doses.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '17','ctg_env_desc' => 'Multidose container with airless pump','ctg_env_obs' => 'Multidose container with an integral pump designed to protect the contents against in use-contamination.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '18','ctg_env_desc' => 'Multidose container with metering pump','ctg_env_obs' => 'Multidose container with integral metering pump.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '19','ctg_env_desc' => 'Multidose container with pump','ctg_env_obs' => 'Multidose container with an integral pump. Metering pump, spray pump, and multidose container with airless pump are excluded.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '20','ctg_env_desc' => 'Pre-filled gastroenteral tube','ctg_env_obs' => 'Pre-filled tube for the administration of a medicinal product to the gastroenteral tract.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '21','ctg_env_desc' => 'Pre-filled injector','ctg_env_obs' => 'Filled container, usually fitted with an injection needle, containing a sterile, single-dose parenteral preparation. This term is only to be used when a more-specific term such as "Pre-filled syringe" or "Pre-filled pen" is not appropriate. This term','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '22','ctg_env_desc' => 'Pre-filled oral applicator','ctg_env_obs' => 'Filled container for administering a liquid or semi-solid pharmaceutical form to the oral cavity, containing the final preparation in one compartment, or the components necessary for its preparation in different compartments. This term may be used to','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '23','ctg_env_desc' => 'Pre-filled oral syringe','ctg_env_obs' => 'Filled container for administering a liquid or semi-solid pharmaceutical form to the oral cavity, containing the final preparation in one compartment, or the components necessary for its preparation in different compartments. For certain products tha','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '24','ctg_env_desc' => 'Pre-filled pen','ctg_env_obs' => 'Filled container consisting for example, of a cartridge, fitted with an injection needle. The cartridge contains a sterile single-dose or multidose parenteral preparation. It contains the final preparation in one compartment, or the components necess','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '25','ctg_env_desc' => 'Pre-filled syringe','ctg_env_obs' => 'Filled container, generally supplied with an injection needle. It contains a sterile single-dose or multidose parenteral preparation. It contains the final preparation in one compartment, or the components necessary for its preparation in different c','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '26','ctg_env_desc' => 'Pressurised container','ctg_env_obs' => 'Container suited for compressed, liquefied or dissolved gas fitted with a device to enable, after its actuation, a controlled spontaneous release of the contents at atmospheric pressure and room temperature.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '27','ctg_env_desc' => 'Roll-on container','ctg_env_obs' => 'A container, usually a bottle, fitted with a roll-on applicator','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '28','ctg_env_desc' => 'Sachet','ctg_env_obs' => 'Container consisting of two surfaces made of flexible material to be closed only by sealing or folding over. The contents are intended for single use.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '12','ctg_env_desc' => 'Fixed cryogenic vessel','ctg_env_obs' => 'A static thermally insulated container desgined to maintain the contents in the liquid state','ctg_tpr_id' => '02','ctg_env_sta' => '2','ctg_env_usr' => '803223','ctg_env_dt' => '2017-10-20 00:29:09'),
            array('ctg_env_id' => '10','ctg_env_desc' => 'Dredging container','ctg_env_obs' => 'Container for a pharmaceutical form to be applied by dredging.','ctg_tpr_id' => '02','ctg_env_sta' => '2','ctg_env_usr' => '803223','ctg_env_dt' => '2017-10-20 00:30:29'),
            array('ctg_env_id' => '29','ctg_env_desc' => 'Single-dose container','ctg_env_obs' => 'A container that holds a quantity of the preparation intended for total or partial use on one occasion only.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '30','ctg_env_desc' => 'Spray container','ctg_env_obs' => 'Container for a liquid pharmaceutical form to be converted into a spray by mechanical means.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '31','ctg_env_desc' => 'Straw','ctg_env_obs' => 'Hollow tube containing a single dose of a medicinal product for oral administration by sucking','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '32','ctg_env_desc' => 'Strip','ctg_env_obs' => 'Multidose container consisting of two layers, usually provided with perforations, suited for containing single doses of solid or semi-solid preparations. Blisters are excluded.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '33','ctg_env_desc' => 'Tablet container','ctg_env_obs' => 'Container without neck and with a flat bottom, suited for tablets, capsules, etc., can be re-closed well.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '34','ctg_env_desc' => 'Tube','ctg_env_obs' => 'Container for semi-solid pharmaceutical forms, usually multidose, consisting of collapsible material intended to release the contents via a nozzle by squeezing the package.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '35','ctg_env_desc' => 'Unit-dose blister','ctg_env_obs' => 'Container consisting of two layers of which one is shaped to contain the individual unit, usually provided with perforations, the intention being to allow each individual unit to be separated for single unit administration. All the information requir','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => '36','ctg_env_desc' => 'Vial','ctg_env_obs' => 'Small container for parenteral medicinal products, with a stopper and overseal; the contents are removed after piercing the stopper. Single-dose and multidose uses are included.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => 'MASTER','ctg_env_dt' => '2017-10-19 17:00:00'),
            array('ctg_env_id' => 'NA','ctg_env_desc' => 'Data not available','ctg_env_obs' => '','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => '803223','ctg_env_dt' => '2017-10-27 23:20:02'),
            array('ctg_env_id' => '888','ctg_env_desc' => 'Ampoule','ctg_env_obs' => 'Container sealed by fusion and to be opened exclusively by breaking. The contents are intended for use on one occasion only.','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => '803223','ctg_env_dt' => '2017-10-27 23:20:58'),
            array('ctg_env_id' => '9999','ctg_env_desc' => 'UNASSIGNED','ctg_env_obs' => '','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => '803223','ctg_env_dt' => '2017-12-13 03:18:35'),
            array('ctg_env_id' => 'MULTI','ctg_env_desc' => 'MULTIPLE - SEE PACK AND INGREDIENT DESCRIPTION','ctg_env_obs' => '','ctg_tpr_id' => '02','ctg_env_sta' => '1','ctg_env_usr' => '803223','ctg_env_dt' => '2018-05-26 23:43:33')
          );

        foreach ($primary_containers as $key => $primary_container) {
            PrimaryContainer::create([
                'name' => $primary_container['ctg_env_id'],
                'description' => $primary_container['ctg_env_desc'],
                'addon' => json_encode($primary_container)
            ]);
        }
    }
}